before_install:
  - "echo '--colour' > ~/.rspec"
  - "echo 'gem: --no-document' > ~/.gemrc"
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
install:
  - bin/setup
branches:
  only:
    - master
cache:
  - bundler
language:
  - ruby
notifications:
  email: false
rvm:
  - 2.2.1
addons:
  postgresql: "9.3"
sudo: false
deploy:
  provider: heroku
  api_key: 1e910af9-0db1-4f6d-a9b7-0632db5be05b
  on:
    all_branches: true
  app:
    master: doctolib-app-production
    develop: doctolib-app-staging
  run:
    - "rake db:migrate"
    - "rake db:setup"
    - "rake cleanup"
    - "rake db:seed"
