require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe Admin::MedicalSpecialitiesController, :type => :controller do

  # This should return the minimal set of attributes required to create a valid
  # MedicalSpeciality. As you add validations to MedicalSpeciality, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    { name: 'Dentiste' }
  }

  let(:invalid_attributes) {
    { name: nil }
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # MedicalSpecialitiesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all medical_specialities as @medical_specialities" do
      medical_speciality = MedicalSpeciality.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:medical_specialities)).to eq([medical_speciality])
    end
  end

  describe "GET show" do
    it "assigns the requested medical_speciality as @medical_speciality" do
      medical_speciality = MedicalSpeciality.create! valid_attributes
      get :show, {:id => medical_speciality.to_param}, valid_session
      expect(assigns(:medical_speciality)).to eq(medical_speciality)
    end
  end

  describe "GET new" do
    it "assigns a new medical_speciality as @medical_speciality" do
      get :new, {}, valid_session
      expect(assigns(:medical_speciality)).to be_a_new(MedicalSpeciality)
    end
  end

  describe "GET edit" do
    it "assigns the requested medical_speciality as @medical_speciality" do
      medical_speciality = MedicalSpeciality.create! valid_attributes
      get :edit, {:id => medical_speciality.to_param}, valid_session
      expect(assigns(:medical_speciality)).to eq(medical_speciality)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new MedicalSpeciality" do
        expect {
          post :create, {:medical_speciality => valid_attributes}, valid_session
        }.to change(MedicalSpeciality, :count).by(1)
      end

      it "assigns a newly created medical_speciality as @medical_speciality" do
        post :create, {:medical_speciality => valid_attributes}, valid_session
        expect(assigns(:medical_speciality)).to be_a(MedicalSpeciality)
        expect(assigns(:medical_speciality)).to be_persisted
      end

      it "redirects to the created medical_speciality" do
        post :create, {:medical_speciality => valid_attributes}, valid_session
        expect(response).to redirect_to(MedicalSpeciality.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved medical_speciality as @medical_speciality" do
        post :create, {:medical_speciality => invalid_attributes}, valid_session
        expect(assigns(:medical_speciality)).to be_a_new(MedicalSpeciality)
      end

      it "re-renders the 'new' template" do
        post :create, {:medical_speciality => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      let(:new_attributes) {
        { name: 'Médecin' }
      }

      it "updates the requested medical_speciality" do
        medical_speciality = MedicalSpeciality.create! valid_attributes
        put :update, {:id => medical_speciality.to_param, :medical_speciality => new_attributes}, valid_session
        medical_speciality.reload
        expect(medical_speciality.name).to eq('Médecin')
      end

      it "assigns the requested medical_speciality as @medical_speciality" do
        medical_speciality = MedicalSpeciality.create! valid_attributes
        put :update, {:id => medical_speciality.to_param, :medical_speciality => valid_attributes}, valid_session
        expect(assigns(:medical_speciality)).to eq(medical_speciality)
      end

      it "redirects to the medical_speciality" do
        medical_speciality = MedicalSpeciality.create! valid_attributes
        put :update, {:id => medical_speciality.to_param, :medical_speciality => valid_attributes}, valid_session
        expect(response).to redirect_to(medical_speciality)
      end
    end

    describe "with invalid params" do
      it "assigns the medical_speciality as @medical_speciality" do
        medical_speciality = MedicalSpeciality.create! valid_attributes
        put :update, {:id => medical_speciality.to_param, :medical_speciality => invalid_attributes}, valid_session
        expect(assigns(:medical_speciality)).to eq(medical_speciality)
      end

      it "re-renders the 'edit' template" do
        medical_speciality = MedicalSpeciality.create! valid_attributes
        put :update, {:id => medical_speciality.to_param, :medical_speciality => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested medical_speciality" do
      medical_speciality = MedicalSpeciality.create! valid_attributes
      expect {
        delete :destroy, {:id => medical_speciality.to_param}, valid_session
      }.to change(MedicalSpeciality, :count).by(-1)
    end

    it "redirects to the medical_specialities list" do
      medical_speciality = MedicalSpeciality.create! valid_attributes
      delete :destroy, {:id => medical_speciality.to_param}, valid_session
      expect(response).to redirect_to(medical_specialities_url)
    end
  end

end
